DROP TABLE IF EXISTS hardware;
CREATE TABLE hardware (
    id IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL,
    amount INT NOT NULL,
    price DOUBLE NOT NULL
);

DROP TABLE IF EXISTS review;
CREATE TABLE review (
    id IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    text VARCHAR(624) NOT NULL,
    rating INT NOT NULL,
    hardwareid LONG
);